name: Update Commit Badge

on:
  schedule:
    - cron: '0 0 * * MON' # Runs every Monday at 00:00 UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Count 2024 Commits
        id: commit_count
        run: |
          COUNT=$(git rev-list --count HEAD --since="2024-01-01" --until="2024-12-31")
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          # Replace the commit count in the badge
          sed -i "s/Commits%20in%202024-[0-9]*/Commits%20in%202024-${{ steps.commit_count.outputs.count }}/" README.md

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update 2024 commit count badge [skip ci]"
          file_pattern: README.md

